### ISSUE TITLE
Add ignore test per version mechanism

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-rust-driver-matrix#9]
Example:
in `v0.11.1` version the test `transport::cql_types_test::test_naive_date` should be ignored - issue https://github.com/scylladb/scylla-rust-driver/issues/991

**Comment by fruch** [comment]
- https://github.com/scylladb/scylla-rust-driver-matrix/pull/11

**Comment by juliayakovlev** [comment]
Revolved with https://github.com/scylladb/scylla-rust-driver-matrix/pull/11
